module.exports = {
  REQUIRE_AUTH: 'It should require authorization',
  CREATE_USER: 'Create user',
  CREATE_USER_EXPECTED: 'It should create a user if already doesn\'t exist',
  TEST: 'test',
  USER_NOT_EXIST: 'User does not exist',
  USER_ALREADY_EXISTS: 'User already exists',
  SOMETHING_WENT_WRONG: 'Something went wrong',
  USER_CREATED: 'User created successfully',
  VALID_EMAIL: 'Please enter valid e-mail address',
  INVALID_CREDENTIALS: 'Invalid credentials',
  LOGGED_IN: 'Logged in',
  REQUEST_VALIDATION: 'Please provide email, password and name',
  REQUEST_VALIDATION_LOGIN: 'Please provide email, password and name',
  LOCATION: 'New Delhi',
  METRIC: 'metric',
  LOG_IN: 'It should log in test user',
  GET_TOKEN: 'It should return token',
  FETCH_NEWS: 'Fetch news',
  FETCH_TOP_HEADLINES: 'It should fetch top headlines with status 200',
  FETCH_BY_KEYWORD: 'It should fetch news by given keyword with status 200',
  FETCH_WEATHER: 'Fetch weather forecast',
  GET_FORECAST: 'It should fetch 5 days weather forecast with status 200'
};
